# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fterm < Formula
  desc "Fterm is a run configuration manager for flutter"
  homepage "https://github.com/siquitch/fterm/"
  version "0.46"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/siquitch/fterm/releases/download/v0.46/fterm_Darwin_x86_64.tar.gz"
      sha256 "e79be9b7b12cf4521ad8f7cd5dbc6f0ab81cf88e5495490d9b68cbaa213b9ce5"

      def install
        bin.install "fterm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/siquitch/fterm/releases/download/v0.46/fterm_Darwin_arm64.tar.gz"
      sha256 "3722f6b3414227b57ae119e34ffabd013d833b1d2cd99e10039331bff7e3a86f"

      def install
        bin.install "fterm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/siquitch/fterm/releases/download/v0.46/fterm_Linux_x86_64.tar.gz"
      sha256 "a854545a9afae642d9b190f3b56ace549492000f9aa1d6a9dae7dff55661c750"
      def install
        bin.install "fterm"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/siquitch/fterm/releases/download/v0.46/fterm_Linux_arm64.tar.gz"
      sha256 "73f571b7c0a767b3da0ce22f523418ed9d7fb001a513eda041b37753959170cb"
      def install
        bin.install "fterm"
      end
    end
  end
end
